# Generated by Django 3.2 on 2022-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(max_length=150, verbose_name='Start Date'),
        ),
    ]
